geolocation:
  latitude: 21.016670030245
  longitude: -89.725788249961
  ciudad: Yucatán

gallery:
  folder: ~/Pictures/kiosk-gallery/
  refresh_interval: 30

weather:
  refresh_interval: 900

calendar:
  enabled: true
  url: "webcal://p34-caldav.icloud.com/published/2/MjAzMzEzOTg3OTkyMDMzMRQrZdVLaHB_Jr_GmUcHKH6snZm-ed5k65xuEL0v5xbBZz8LbrL2EI33mQJx0ZPn82f5JsQfHFfAghvAuLqD6Yg"
  refresh_interval: 3600
  max_events: 31
  days_ahead: 31